recipe: default.v1
language: en
assistant_id: se-take-home-test-2026H1

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: LogisticRegressionClassifier
  - name: NLUCommandAdapter
  - name: SearchReadyLLMCommandGenerator
    llm:
      model_group: gpt-4o
    flow_retrieval:
      active: false

policies:
- name: FlowPolicy
- name: EnterpriseSearchPolicy
  vector_store:
    type: "faiss"
    source: "./docs"
  llm:
    model_group: gpt-4o